### ISSUE TITLE
Authorise Craft problem

### ISSUE THREAD

**Issue by helenc77** [scaramangagency/craftagram#79]
I'm installing the plugin on a localhost server first. When I get to the Authorise Craft button that seems to take me to my live site to try and complete the process where Craftagram isn't installed yet (I added all 3 urls local, staging, live to OAuth redirect URIs in Meta). I wondered if it was authorised anyway as it works locally, but when I upload my code changes to the staging site it doesn't seem to work. I'm probably doing something wrong, can you help? thanks

**Comment by jsmrtn** [comment]
This should be resolved in 4.1.0.

I've reverted back to autogenerated embed URLs that will send through the `BASE_URL` of the site you are currently on, as I had overlooked that the manual copy from `developers.facebook.com` will only have one URL available to it, which won't necessarily be the localhost URL.

This should hopefully mean you can fetch a token for + return to the correct site.

**Comment by helenc77** [comment]
Thanks Josh. That now takes me back to the correct site on local and staging with the long access token populated. The button still says 'Authorize Craft' though, is that as it should be? I ask because I'm still not seeing the images on the staging site (they are appearing in the preview, and locally though). Sorry to be a right annoyance with so many problems! Is there anything I need to do at server level to make sure they're not getting blocked somehow?

**Comment by jsmrtn** [comment]
Yeah the button is just called that – it's just how I named it (i.e Authorise Craft to access Instagram).

So to clarify, you see the images in the preview in the admin panel, but when you use it on the front end of your website you do not get the images load? How are you integrating on the FE, just the basic example from the README?

**Comment by helenc77** [comment]
You're right, there was some errors in my code which I'd partially copied from the readme but not entirely! Now fixed thanks :)
